spin_manifest_version = "1"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = ""
name = "goodbye"
trigger = { type = "pg-event" }
version = "0.1.0"

[[component]]
id = "test"
source = "test/target/wasm32-wasi/release/pg_test.wasm"
[component.trigger]
table = "test"
[component.build]
workdir = "test"
command = "cargo build --target wasm32-wasi --release"

[[component]]
id = "test2"
source = "test2/target/wasm32-wasi/release/moar_guest.wasm"
[component.trigger]
table = "test2"
[component.build]
workdir = "test2"
command = "cargo build --target wasm32-wasi --release"
